In [6]:
import duckdb
con = duckdb.connect("../data/barca.duckdb", read_only=True)
xg_season = con.sql(open("../sql/01_xg_per_player_season.sql").read()).df()
xg_season

,season,player,shots,goals,xg
315,2020/2021,Lionel Andrés Messi Cuccittini,195,30.0,22.87
316,2020/2021,Antoine Griezmann,64,12.0,12.55
317,2020/2021,Ousmane Dembélé,47,5.0,4.54
318,2020/2021,Martin Braithwaite Christensen,22,2.0,4.35
319,2020/2021,Frenkie de Jong,15,2.0,4.21
320,2020/2021,Philippe Coutinho Correia,27,2.0,3.69
321,2020/2021,Pedro González López,22,3.0,3.64
322,2020/2021,Francisco António Machado Mota de Castro Trincão,20,3.0,2.39
323,2020/2021,Jordi Alba Ramos,24,3.0,1.96
324,2020/2021,Ronald Federico Araújo da Silva,10,2.0,1.79
325,2020/2021,Sergino Dest,14,2.0,1.77
326,2020/2021,Anssumane Fati,14,4.0,1.62
327,2020/2021,Clément Lenglet,10,1.0,1.34
328,2020/2021,Moriba Kourouma Kourouma,13,1.0,1.15
329,2020/2021,Miralem Pjanić,14,0.0,0.97
330,2020/2021,Óscar Mingueza García,9,2.0,0.80
331,2020/2021,Héctor Junior Firpo Adames,1,1.0,0.78
332,2020/2021,Gerard Piqué Bernabéu,8,0.0,0.62
333,2020/2021,Sergi Roberto Carnicer,5,1.0,0.43
334,2020/2021,Sergio Busquets i Burgos,2,0.0,0.20
335,2020/2021,Samuel Yves Umtiti,2,0.0,0.13
336,2020/2021,Ricard Puig Martí,3,0.0,0.13
337,2020/2021,Marc-André ter Stegen,1,0.0,0.06
338,2020/2021,Carles Aleña Castillo,1,0.0,0.04

In [10]:
xg_for_against = con.sql(open("../sql/02_xg_for_vs_against.sql").read()).df()
xg_for_against

,season,matches,xg_for,xg_against,xg_for_per_match,xg_against_per_match
0,2004/2005,7,9.7,3.6,1.39,0.51
1,2005/2006,17,39.1,12.6,2.30,0.74
2,2006/2007,26,47.2,22.6,1.82,0.87
3,2007/2008,27,45.4,25.9,1.68,0.96
4,2008/2009,31,72.5,19.1,2.34,0.62
5,2009/2010,35,63.7,26.7,1.82,0.76
6,2010/2011,33,61.5,23.0,1.86,0.70
7,2011/2012,37,81.4,27.8,2.20,0.75
8,2012/2013,32,55.0,29.2,1.72,0.91
9,2013/2014,31,64.1,25.4,2.07,0.82
10,2014/2015,38,84.1,26.7,2.21,0.70
11,2015/2016,38,91.4,32.7,2.41,0.86
12,2016/2017,34,74.1,28.2,2.18,0.83
13,2017/2018,36,74.8,34.4,2.08,0.96
14,2018/2019,34,62.2,34.9,1.83,1.03
15,2019/2020,33,55.3,31.0,1.68,0.94
16,2020/2021,35,72.0,35.4,2.06,1.01

In [13]:
xg_goals_coach = con.sql(open("../sql/03_goals_vs_xg_by_coach.sql").read()).df()
xg_goals_coach

,barca_coach,first_match,matches,goals,total_xg,goals_minus_xg
0,Frank Rijkaard,2004-10-16,77,171.0,141.4,29.6
1,Josep Guardiola i Sala,2008-08-31,136,384.0,279.1,104.9
2,Francesc Vilanova i Bayo,2012-08-19,32,98.0,55.0,43.0
3,Gerardo Daniel Martino,2013-08-18,31,80.0,64.1,15.9
4,Luis Enrique Martínez García,2014-08-24,110,326.0,249.6,76.4
5,Ernesto Valverde Tejedor,2017-08-20,84,210.0,158.6,51.4
6,Enrique Setién Solar,2020-01-19,19,37.0,33.7,3.3
7,Ronald Koeman,2020-09-27,35,81.0,72.0,9.0

In [12]:
goals_game_state = con.sql(open("../sql/04_goals_by_game_state.sql").read()).df()
goals_game_state

  game_state  barca_goals
0    Winning          714
1    Drawing          498
2     Losing          135

In [15]:
top_xa = con.sql(open("../sql/05_top_xa.sql").read()).df()
top_xa

                            player  key_passes      xa
0   Lionel Andrés Messi Cuccittini        1061  142.49
1           Xavier Hernández Creus         570   55.55
2         Luis Alberto Suárez Díaz         298   46.45
3            Daniel Alves da Silva         342   43.14
4             Andrés Iniesta Luján         382   42.61
5    Neymar da Silva Santos Junior         263   33.36
6                 Jordi Alba Ramos         255   32.82
7         Sergio Busquets i Burgos         217   22.93
8        Francesc Fàbregas i Soler         120   19.72
9  Pedro Eliezer Rodríguez Ledesma         151   18.65